name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        qt-version: [5, 6]
        include:
          - qt-version: 6
            qt-base: 'qt6-base-dev'
            qt-multimedia: 'qt6-multimedia-dev'
          - qt-version: 5
            qt-base: 'qtbase5-dev'
            qt-multimedia: 'qtmultimedia5-dev'
            param: -DQT6=OFF

    steps:
    - name: install_qt_deps
      run: |
        sudo apt-get update
        sudo apt-get install ${{ matrix.qt-base }} ${{ matrix.qt-multimedia }}
    - name: install_deps
      run: sudo apt-get install cmake gettext libsndfile1-dev libmpg123-dev libvorbis-dev libopusfile-dev libgme-dev libsidplayfp-dev libstilview-dev libopenmpt-dev libmpcdec-dev libwavpack-dev libavcodec-dev libavformat-dev libbs2b-dev
    - uses: actions/checkout@v4
    - name: build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug ${{ matrix.param }} ..
        cmake --build .
