name: Release

on:
  release:
     types: [published]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          zip
          upx
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-gettext
          mingw-w64-x86_64-qt5-static
          mingw-w64-x86_64-libsndfile
          mingw-w64-x86_64-mpg123
          mingw-w64-x86_64-libvorbis
          mingw-w64-x86_64-opusfile
          mingw-w64-x86_64-libgme
          mingw-w64-x86_64-libmpcdec
          mingw-w64-x86_64-wavpack
          mingw-w64-x86_64-ffmpeg
          mingw-w64-x86_64-libbs2b
          mingw-w64-x86_64-libsidplayfp
          mingw-w64-x86_64-libopenmpt
          mingw-w64-x86_64-liblastfm
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Get the tag name
      id: get_tag_name
      run: echo ::set-output name=tagname::${GITHUB_REF#refs/tags/v}
    - name: build
      run: |
        mkdir build
        cd build
        cmake -G 'MSYS Makefiles' \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc -static-libstdc++" \
            ..
        make VERBOSE=1
    - name: package
      run: |
        export PACKAGE_NAME=musiqt-${{ steps.get_tag_name.outputs.tagname }}-w64
        mkdir ${PACKAGE_NAME}
        cp README ${PACKAGE_NAME}
        cp build/musiqt.exe ${PACKAGE_NAME}
        strip ${PACKAGE_NAME}/musiqt.exe
        upx ${PACKAGE_NAME}/musiqt.exe || true
        mkdir -p ${PACKAGE_NAME}/locale/es/LC_MESSAGES
        cp build/es.gmo ${PACKAGE_NAME}/locale/es/LC_MESSAGES/musiqt.mo
        mkdir -p ${PACKAGE_NAME}/locale/it/LC_MESSAGES
        cp build/it.gmo ${PACKAGE_NAME}/locale/it/LC_MESSAGES/musiqt.mo
        cp  /mingw64/bin/libsndfile-1.dll \
            /mingw64/bin/libmpg123-0.dll \
            /mingw64/bin/libvorbis-0.dll \
            /mingw64/bin/libvorbisfile-3.dll \
            /mingw64/bin/libopusfile-0.dll \
            /mingw64/bin/libgme.dll \
            /mingw64/bin/libwavpack-1.dll \
            /mingw64/bin/libmpcdec-6.dll \
            /mingw64/bin/libsidplayfp-6.dll \
            /mingw64/bin/libstilview-0.dll \
            /mingw64/bin/libopenmpt-0.dll \
            /mingw64/bin/liblastfm5-1.dll \
            /mingw64/bin/libgettextlib-0-19-8-1.dll \
            /mingw64/bin/libintl-8.dll \
            ${PACKAGE_NAME}
        zip -r ${PACKAGE_NAME}.zip ${PACKAGE_NAME}/*
    - uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: musiqt-${{ steps.get_tag_name.outputs.tagname }}-w64.zip
        tag: ${{ github.ref }}
        file_glob: true
        overwrite: true
