name: Release

on:
  release:
     types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          zip
          upx
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-gettext
          mingw-w64-x86_64-qt6-base
          mingw-w64-x86_64-qt6-shadertools
          mingw-w64-x86_64-qt6-multimedia
          mingw-w64-x86_64-libsndfile
          mingw-w64-x86_64-mpg123
          mingw-w64-x86_64-libvorbis
          mingw-w64-x86_64-opusfile
          mingw-w64-x86_64-libgme
          mingw-w64-x86_64-libmpcdec
          mingw-w64-x86_64-wavpack
          mingw-w64-x86_64-ffmpeg
          mingw-w64-x86_64-libbs2b
          mingw-w64-x86_64-libsidplayfp
          mingw-w64-x86_64-libopenmpt
          mingw-w64-x86_64-liblastfm
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Get the tag name
      id: get_tag_name
      run: echo "tagname=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    - name: build
      run: |
        mkdir build
        cd build
        cmake -G 'MSYS Makefiles' \
            -DCMAKE_BUILD_TYPE=Release \
            -DQT6=ON \
            -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc -static-libstdc++" \
            ..
        cmake --build .
    - name: package
      run: |
        export PACKAGE_NAME=musiqt-${{ steps.get_tag_name.outputs.tagname }}-w64
        mkdir ${PACKAGE_NAME}
        cp README.md ${PACKAGE_NAME}
        cp build/musiqt.exe ${PACKAGE_NAME}
        strip ${PACKAGE_NAME}/musiqt.exe
        upx ${PACKAGE_NAME}/musiqt.exe || true
        mkdir -p ${PACKAGE_NAME}/locale/es/LC_MESSAGES
        cp build/es.gmo ${PACKAGE_NAME}/locale/es/LC_MESSAGES/musiqt.mo
        mkdir -p ${PACKAGE_NAME}/locale/it/LC_MESSAGES
        cp build/it.gmo ${PACKAGE_NAME}/locale/it/LC_MESSAGES/musiqt.mo
        ldd ${PACKAGE_NAME}/musiqt.exe |grep -vi Windows|awk '{ print $3 }' | while read file ; do cp "$file" ${PACKAGE_NAME} ; done
        strip ${PACKAGE_NAME}/*.dll
        windeployqt6.exe --no-translations ${PACKAGE_NAME}/musiqt.exe
        zip -r ${PACKAGE_NAME}.zip ${PACKAGE_NAME}/*
    - name: build-portable
      run: |
        mkdir build-portable
        cd build-portable
        cmake -G 'MSYS Makefiles' \
            -DCMAKE_BUILD_TYPE=Release \
            -DQT6=ON \
            -DPORTABLE=ON \
            -DCMAKE_EXE_LINKER_FLAGS="-static-libgcc -static-libstdc++" \
            ..
        cmake --build .
    - name: package-portable
      run: |
        export PACKAGE_NAME=musiqt-${{ steps.get_tag_name.outputs.tagname }}-w64-portable
        mkdir ${PACKAGE_NAME}
        cp README.md ${PACKAGE_NAME}
        cp build-portable/musiqt.exe ${PACKAGE_NAME}
        strip ${PACKAGE_NAME}/musiqt.exe
        upx ${PACKAGE_NAME}/musiqt.exe || true
        for locale in {'es','it'}; do
            mkdir -p ${PACKAGE_NAME}/locale/${locale}/LC_MESSAGES
            cp build-portable/${locale}.gmo ${PACKAGE_NAME}/locale/${locale}/LC_MESSAGES/musiqt.mo
        done
        ldd ${PACKAGE_NAME}/musiqt.exe |grep -vi Windows|awk '{ print $3 }' | while read file ; do cp "$file" ${PACKAGE_NAME} ; done
        strip ${PACKAGE_NAME}/*.dll
        windeployqt6.exe --no-translations ${PACKAGE_NAME}/musiqt.exe
        zip -r ${PACKAGE_NAME}.zip ${PACKAGE_NAME}/*
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: musiqt-${{ steps.get_tag_name.outputs.tagname }}-w64*.zip
        tag: ${{ github.ref }}
        file_glob: true
        overwrite: true
